require: rubocop-rspec

inherit_gem:
  govuk-lint: "configs/rubocop/all.yml"

CaseIndentation:
  Enabled: false

Style/MutableConstant:
  Enabled: false

EmptyLineBetweenDefs:
  Enabled: false

TrailingBlankLines:
  Enabled: false

MethodCalledOnDoEndBlock:
  Enabled: false

MultilineBlockChain:
  Enabled: false

ParenthesesAroundCondition:
  Enabled: false

UnusedBlockArgument:
  Enabled: false

VariableName:
  Enabled: false

AmbiguousRegexpLiteral:
  Enabled: false

AssignmentInCondition:
  Enabled: false

HandleExceptions:
  Enabled: false

ParenthesesAsGroupedExpression:
  Enabled: false

ShadowingOuterLocalVariable:
  Enabled: false

UselessAssignment:
  Enabled: false

Void:
  Enabled: false

ParallelAssignment:
  Enabled: false

UnneededPercentQ:
  Enabled: false

EmptyLinesAroundModuleBody:
  Enabled: false

EmptyLinesAroundBeginBody:
  Enabled: false

EmptyLinesAroundBlockBody:
  Enabled: false

RedundantBlockCall:
  Enabled: false

UnneededInterpolation:
  Enabled: false

EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false

StringReplacement:
  Enabled: false

MultilineMethodCallBraceLayout:
  Enabled: false

ExtraSpacing:
  Enabled: false

DateTime:
  Enabled: false

SymbolProc:
  Enabled: false

AmbiguousBlockAssociation:
  Enabled: false

BlockLength:
  Enabled: false

NumericPredicate:
  Enabled: false

ZeroLengthPredicate:
  Enabled: false

RangeInclude:
  Enabled: false

MultilineIfModifier:
  Enabled: false

ConditionalAssignment:
  Enabled: false

IfInsideElse:
  Enabled: false

InverseMethods:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/WordArray:
  Enabled: false
