version: '2'
services:
  api:
    container_name: api
    stdin_open: true
    tty: true
    restart: always
    image: "digitalmarketplace/api:latest"
    ports:
      - "5000:80"
    environment:
      - DM_ENVIRONMENT=development
      - DM_SEARCH_API_URL=http://search-api:80
      - SQLALCHEMY_DATABASE_URI=postgresql://dmdev:dmdevpasswd@postgres:5432/digitalmarketplace
    volumes:
      - ./compose-scripts:/compose-scripts
      - "${DM_DATA_API_DEVELOPMENT_REPO}:/repo"
    working_dir: /repo
    command: >
      bash -c 'ln -sf /dev/stdout /var/log/digitalmarketplace/application.log &&
      sed -i -e "s/stdout_logfile_maxbytes = [0-9]*/stdout_logfile_maxbytes = 0/g" /etc/supervisord.conf &&
      /compose-scripts/wait-for-postgres.py && python application.py db upgrade &&
      make virtualenv && python application.py runserver  --host 0.0.0.0 --port 80'
    depends_on:
      - postgres

  search-api:
    container_name: search-api
    stdin_open: true
    tty: true
    restart: always
    image: "digitalmarketplace/search-api:latest"
    ports:
      - "5001:80"
    environment:
      - DM_ENVIRONMENT=development
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    volumes:
      - "${DM_SEARCH_API_DEVELOPMENT_REPO}:/repo"
    working_dir: /repo
    command:
      bash -c 'ln -sf /dev/stdout /var/log/digitalmarketplace/application.log &&
      sed -i -e "s/stdout_logfile_maxbytes = [0-9]*/stdout_logfile_maxbytes = 0/g" /etc/supervisord.conf &&
      make virtualenv && python application.py runserver --host 0.0.0.0 --port 80'
    depends_on:
      - elasticsearch

  user-frontend:
    container_name: user-frontend
    stdin_open: true
    tty: true
    restart: always
    image: "digitalmarketplace/user-frontend:latest"
    ports:
      - "5007:80"
    environment:
      - DM_ENVIRONMENT=development
      - DM_DATA_API_URL=http://api:80
      - DM_NOTIFY_API_KEY=${DM_NOTIFY_API_KEY}
      - PROXY_AUTH_CREDENTIALS=dev-user:$$apr1$$rx3G14WQ$$I2zOn60wfMGCrxjC8NbdP0
    volumes:
      - ./compose-scripts:/compose-scripts
      - "${DM_USER_FRONTEND_DEVELOPMENT_REPO}:/repo"
    command: >
      bash -c 'ln -sf /dev/stdout /var/log/digitalmarketplace/application.log &&
      sed -i -e "s/stdout_logfile_maxbytes = [0-9]*/stdout_logfile_maxbytes = 0/g" /etc/supervisord.conf &&
      /compose-scripts/wait-for-api.sh && make virtualenv && python application.py runserver --host 0.0.0.0 --port 80'
    working_dir: /repo
    depends_on:
      - api

  buyer-frontend:
    container_name: buyer-frontend
    stdin_open: true
    tty: true
    restart: always
    image: "digitalmarketplace/buyer-frontend:latest"
    ports:
      - "5002:80"
    environment:
      - DM_ENVIRONMENT=development
      - DM_DATA_API_URL=http://api:80
      - DM_SEARCH_API_URL=http://search-api:80
      - DM_MANDRILL_API_KEY=${DM_MANDRILL_API_KEY}
      - PROXY_AUTH_CREDENTIALS=dev-user:$$apr1$$rx3G14WQ$$I2zOn60wfMGCrxjC8NbdP0
    volumes:
      - ./compose-scripts:/compose-scripts
      - "${DM_BUYER_FRONTEND_DEVELOPMENT_REPO}:/repo"
    command: >
      bash -c 'ln -sf /dev/stdout /var/log/digitalmarketplace/application.log &&
      sed -i -e "s/stdout_logfile_maxbytes = [0-9]*/stdout_logfile_maxbytes = 0/g" /etc/supervisord.conf &&
      /compose-scripts/wait-for-api.sh && make virtualenv && python application.py runserver --host 0.0.0.0 --port 80'
    working_dir: /repo
    depends_on:
      - api
      - search-api

  briefs-frontend:
    container_name: briefs-frontend
    stdin_open: true
    tty: true
    restart: always
    image: "digitalmarketplace/briefs-frontend:latest"
    ports:
      - "5005:80"
    environment:
      - DM_ENVIRONMENT=development
      - DM_DATA_API_URL=http://api:80
      - DM_NOTIFY_API_KEY=${DM_NOTIFY_API_KEY}
      - PROXY_AUTH_CREDENTIALS=dev-user:$$apr1$$rx3G14WQ$$I2zOn60wfMGCrxjC8NbdP0
    volumes:
      - ./compose-scripts:/compose-scripts
      - "${DM_BRIEFS_FRONTEND_DEVELOPMENT_REPO}:/repo"
    command: >
      bash -c 'ln -sf /dev/stdout /var/log/digitalmarketplace/application.log &&
      sed -i -e "s/stdout_logfile_maxbytes = [0-9]*/stdout_logfile_maxbytes = 0/g" /etc/supervisord.conf &&
      /compose-scripts/wait-for-api.sh && make virtualenv && python application.py runserver --host 0.0.0.0 --port 80'
    working_dir: /repo
    depends_on:
      - api

  brief-responses-frontend:
    container_name: brief-responses-frontend
    stdin_open: true
    tty: true
    restart: always
    image: "digitalmarketplace/brief-responses-frontend:latest"
    ports:
      - "5006:80"
    environment:
      - DM_ENVIRONMENT=development
      - DM_DATA_API_URL=http://api:80
      - DM_MANDRILL_API_KEY=${DM_MANDRILL_API_KEY}
      - PROXY_AUTH_CREDENTIALS=dev-user:$$apr1$$rx3G14WQ$$I2zOn60wfMGCrxjC8NbdP0
    volumes:
      - ./compose-scripts:/compose-scripts
      - "${DM_BRIEF_RESPONSES_FRONTEND_DEVELOPMENT_REPO}:/repo"
    command: >
      bash -c 'ln -sf /dev/stdout /var/log/digitalmarketplace/application.log &&
      sed -i -e "s/stdout_logfile_maxbytes = [0-9]*/stdout_logfile_maxbytes = 0/g" /etc/supervisord.conf &&
      /compose-scripts/wait-for-api.sh && make virtualenv && python application.py runserver --host 0.0.0.0 --port 80'
    working_dir: /repo
    depends_on:
      - api

  supplier-frontend:
    container_name: supplier-frontend
    stdin_open: true
    tty: true
    restart: always
    image: "digitalmarketplace/supplier-frontend:latest"
    ports:
      - "5003:80"
    environment:
      - DM_ENVIRONMENT=development
      - DM_DATA_API_URL=http://api:80
      - PROXY_AUTH_CREDENTIALS=dev-user:$$apr1$$rx3G14WQ$$I2zOn60wfMGCrxjC8NbdP0
      - DM_NOTIFY_API_KEY=${DM_NOTIFY_API_KEY}
      - DM_MANDRILL_API_KEY=${DM_MANDRILL_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./compose-scripts:/compose-scripts
      - "${DM_SUPPLIER_FRONTEND_DEVELOPMENT_REPO}:/repo"
    command: >
      bash -c 'ln -sf /dev/stdout /var/log/digitalmarketplace/application.log &&
      sed -i -e "s/stdout_logfile_maxbytes = [0-9]*/stdout_logfile_maxbytes = 0/g" /etc/supervisord.conf &&
      /compose-scripts/wait-for-api.sh && make virtualenv && python application.py runserver --host 0.0.0.0 --port 80'
    working_dir: /repo
    depends_on:
      - api

  admin-frontend:
    container_name: admin-frontend
    stdin_open: true
    tty: true
    restart: always
    image: "digitalmarketplace/admin-frontend:latest"
    ports:
      - "5004:80"
    environment:
      - DM_ENVIRONMENT=development
      - DM_DATA_API_URL=http://api:80
      - PROXY_AUTH_CREDENTIALS=dev-user:$$apr1$$rx3G14WQ$$I2zOn60wfMGCrxjC8NbdP0
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - DM_NOTIFY_API_KEY=${DM_NOTIFY_API_KEY}
    volumes:
      - ./compose-scripts:/compose-scripts
      - "${DM_ADMIN_FRONTEND_DEVELOPMENT_REPO}:/repo"
    command: >
      bash -c 'ln -sf /dev/stdout /var/log/digitalmarketplace/application.log &&
      sed -i -e "s/stdout_logfile_maxbytes = [0-9]*/stdout_logfile_maxbytes = 0/g" /etc/supervisord.conf &&
      /compose-scripts/wait-for-api.sh && make virtualenv && python application.py runserver --host 0.0.0.0 --port 80'
    working_dir: /repo
    depends_on:
      - api

  postgres:
    container_name: postgres
    image: "postgres:9.5"
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=dmdev
      - POSTGRES_PASSWORD=dmdevpasswd
      - POSTGRES_DB=digitalmarketplace

  elasticsearch:
    container_name: elasticsearch
    image: "elasticsearch:5.4"
    ports:
      - "9200:9200"

  nginx:
    container_name: nginx
    image: "digitalmarketplace/local-nginx:latest"
    build:
      context: ./
      dockerfile: ./local-nginx.docker
    ports:
      - "80:80"
    depends_on:
      - api
      - search-api
      - user-frontend
      - buyer-frontend
      - briefs-frontend
      - brief-responses-frontend
      - supplier-frontend
      - admin-frontend
