source "https://rubygems.org"

gem "capybara"
gem "capybara-screenshot"
gem "cucumber"
gem "json"
gem "launchy"
gem "nokogiri"
gem "notifications-ruby-client"
gem "parallel_tests"
gem "phantomjs"
gem "poltergeist"
gem "rake"
gem "report_builder"
gem "rest-client"
gem "rspec"
gem "selenium-webdriver"
gem "test-unit"
