#!/bin/bash

export DM_API_DOMAIN=${DM_API_DOMAIN:=http://localhost:5000}
export DM_API_ACCESS_TOKEN=${DM_API_ACCESS_TOKEN:=myToken}
export DM_SEARCH_API_DOMAIN=${DM_API_API_DOMAIN:=http://localhost:5001}
export DM_SEARCH_API_ACCESS_TOKEN=${DM_SEARCH_API_ACCESS_TOKEN:=myToken}
export DM_FRONTEND_DOMAIN=${DM_FRONTEND_DOMAIN:=http://localhost}

export DM_PRODUCTION_SUPPLIER_USER_EMAIL=${DM_PRODUCTION_SUPPLIER_USER_EMAIL:=production-supplier-user@example.com}
export DM_PRODUCTION_SUPPLIER_USER_PASSWORD=${DM_PRODUCTION_SUPPLIER_USER_PASSWORD:=REPLACEME}
export DM_PRODUCTION_SUPPLIER_USER_NAME=${DM_PRODUCTION_SUPPLIER_USER_NAME:="Functional Test Supplier User"}
export DM_PRODUCTION_SUPPLIER_USER_SUPPLIER_ID=${DM_PRODUCTION_SUPPLIER_USER_SUPPLIER_ID:=577184}

export DM_PRODUCTION_BUYER_USER_EMAIL=${DM_PRODUCTION_BUYER_USER_EMAIL:=production-buyer-user@example.gov.uk}
export DM_PRODUCTION_BUYER_USER_PASSWORD=${DM_PRODUCTION_BUYER_USER_PASSWORD:=REPLACEME}
export DM_PRODUCTION_BUYER_USER_NAME=${DM_PRODUCTION_BUYER_USER_NAME:="Functional Test Buyer User"}

export DM_PRODUCTION_ADMIN_USER_EMAIL=${DM_PRODUCTION_ADMIN_USER_EMAIL:=production-admin-user@example.gov.uk}
export DM_PRODUCTION_ADMIN_USER_PASSWORD=${DM_PRODUCTION_ADMIN_USER_PASSWORD:=REPLACEME}
export DM_PRODUCTION_ADMIN_USER_NAME=${DM_PRODUCTION_ADMIN_USER_NAME:="Functional Test Admin User"}

export DM_PRODUCTION_ADMIN_CCS_CATEGORY_USER_EMAIL=${DM_PRODUCTION_ADMIN_CCS_CATEGORY_USER_EMAIL:=production-admin-ccs-category-user@example.gov.uk}
export DM_PRODUCTION_ADMIN_CCS_CATEGORY_USER_PASSWORD=${DM_PRODUCTION_ADMIN_CCS_CATEGORY_USER_PASSWORD:=REPLACEME}
export DM_PRODUCTION_ADMIN_CCS_CATEGORY_USER_NAME=${DM_PRODUCTION_ADMIN_CCS_CATEGORY_USER_NAME:="Functional Test Admin CCS Category User"}

export DM_PRODUCTION_ADMIN_CCS_SOURCING_USER_EMAIL=${DM_PRODUCTION_ADMIN_CCS_SOURCING_USER_EMAIL:=production-admin-ccs-sourcing-user@example.gov.uk}
export DM_PRODUCTION_ADMIN_CCS_SOURCING_USER_PASSWORD=${DM_PRODUCTION_ADMIN_CCS_SOURCING_USER_PASSWORD:=REPLACEME}
export DM_PRODUCTION_ADMIN_CCS_SOURCING_USER_NAME=${DM_PRODUCTION_ADMIN_CCS_SOURCING_USER_NAME:="Functional Test Admin CCS Sourcing User"}

export DM_ADMIN_EMAIL=${DM_ADMIN_EMAIL:=admin@admin.dmdev}
export DM_ADMIN_CCS_SOURCING_EMAIL=${DM_ADMIN_CCS_SOURCING_EMAIL:=ccs-sourcing@example.com}
export DM_ADMIN_CCS_CATEGORY_EMAIL=${DM_ADMIN_CCS_CATEGORY_EMAIL:=ccs-category@example.com}
export DM_ADMIN_PASSWORD=${DM_ADMIN_PASSWORD:=Admin12345}

export DM_BUYER_EMAIL=${DM_BUYER_EMAIL:=digital-marketplace-development+functional-tests-buyer-user@digital.cabinet-office.gov.uk}
export DM_BUYER_PASSWORD=${DM_BUYER_PASSWORD:=testuserpassword}

export DM_SUPPLIER_EMAIL=${DM_SUPPLIER_EMAIL:=testing.supplier.username@dmtestemail.com}
export DM_SUPPLIER2_EMAIL=${DM_SUPPLIER2_EMAIL:=testing.supplier.username2@dmtestemail.com}
export DM_SUPPLIER3_EMAIL=${DM_SUPPLIER3_EMAIL:=testing.supplier.username3@dmtestemail.com}
export DM_SUPPLIER2_USER_EMAIL=${DM_SUPPLIER2_USER_EMAIL:=testing.supplier2.username@dmtestemail.com}
export DM_SUPPLIER_PASSWORD=${DM_SUPPLIER_PASSWORD:=testuserpassword}

export DM_MANDRILL_API_KEY=${DM_MANDRILL_API_KEY:=mandrillKey}
export DM_PAGINATION_LIMIT=${DM_PAGINATION_LIMIT:=5}
